name: Pacman  
on:  
  schedule:  
    - cron: "* * * * *" # Executa a cada minuto  
jobs:  
  pacman:  
    runs-on: ubuntu-latest  
    steps:  
      - name: 'Pacman Contributions'  
        run: |  
          if [[ $(date '+%H') -eq 12 ]]; then  
            echo "Pacman!$(date '+%Y-%m-%d')" >> "README.md"  
            git config --local user.email 'your_email@example.com'  
            git config --local user.name 'your_username'  
            git add README.md  
            git commit -m "Pacman contributions"  
            git push  
          fi  
